#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'About', url: 'pages/about.html'}
- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio for Nathaniel Wernimont '

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
#google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >

  - Career Objectives
  - Resume

contact: >
  # Contact

  You may contact me at nate.wernimont@gmail.com

#-------------------------------
# Work Section

projects:
- {name: 'Project One', folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: 'Project Two', folder: 'proj-2', file: 'projects/proj-2.html'}
- {name: 'Project Three', folder: 'proj-3', file: 'projects/proj-3.html'}
- {name: 'Microsoft', folder: 'microsoft', file: 'projects/microsoft.html'}
- {name: 'Workiva', folder: 'workiva', file: 'projects/workiva.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'instagram', link: '#'}
- {icon: 'linkedin', link: '#'}
- {icon: 'envelope', link: 'mailto:nate.wernimont@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
